language: python
python:
- '2.7'
- '3.3'
- pypy
before_install:
- sudo apt-get update
- sudo apt-get install -y freetds-dev
- sudo pip install --upgrade setuptools
- sudo apt-get install -y libffi-dev libssl-dev
script:
- nosetests
- deploy_sql.py --help
after_script:
- coveralls
